### ISSUE TITLE
Error while generating fingerprint for MP3 file

### ISSUE THREAD

**Issue by deborasetton** [mbortnyck/qfp#2]
Hi,

We're trying to generate a fingerprint for [this MP3 recording](https://github.com/mbortnyck/qfp/files/980472/antonio.zip) and are running into the following error:

```
>>> fp_r = ReferenceFingerprint("antonio.mp3")
>>> fp_r.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/devstation2/dev/mbortnyck/qfp/qfp/fingerprint.py", line 52, in create
    quads = find_quads(self.peaks, r, c)
  File "/Users/devstation2/dev/mbortnyck/qfp/qfp/quads.py", line 14, in find_quads
    quads += _root_quads(root, peaks, r, c)
  File "/Users/devstation2/dev/mbortnyck/qfp/qfp/quads.py", line 22, in _root_quads
    filtered = _filter_peaks(root, peaks, r, c)
  File "/Users/devstation2/dev/mbortnyck/qfp/qfp/quads.py", line 40, in _filter_peaks
    idx_end = bisect_right(peaks, (windowEnd, None))
TypeError: unorderable types: int() > NoneType()
```

Do you know what the issue might be?

Thanks!

**Comment by deborasetton** [comment]
Never mind, it was the Python version. It works with Python 2.7, but not with Python 3.
